import 'package:equatable/equatable.dart';
import 'package:hive/hive.dart';

/// Direction of a user fill.
///
/// Today the app only emits [buy] (the Purchase flow on
/// `AssetDetailScreen`); the field exists so a future Sell button can
/// drop in without a Hive schema migration.
enum FillSide { buy, sell }

/// A single user trade execution: "I bought N units of [symbol] at [price]".
///
/// One [Fill] per accepted purchase. The chart's `FillMarkerOverlay`
/// anchors at the fill's [timestamp] (x) and [price] (y), so users can
/// see exactly where on the curve their entry landed.
///
/// Persisted via Hive — the [TypeAdapter]s in this file are
/// hand-written (no codegen) so the model has no build-step dependency.
/// The on-disk wire format is documented inline on each adapter and
/// must stay backwards-compatible: only ever append new fields with
/// new field IDs.
class Fill extends Equatable {
  const Fill({
    required this.id,
    required this.symbol,
    required this.side,
    required this.price,
    required this.sizeBase,
    required this.costQuote,
    required this.quoteSymbol,
    required this.timestamp,
  });

  /// Stable, globally unique id (used as the Hive key + for tap-to-
  /// inspect routing). Generated by the repository at insert time.
  final String id;

  /// Base asset bought / sold (e.g. `BTC`). Always upper-cased so
  /// per-symbol queries don't have to case-fold.
  final String symbol;

  final FillSide side;

  /// Execution price, denominated in [quoteSymbol].
  final double price;

  /// Size of the fill in [symbol] units (e.g. 0.10 BTC).
  final double sizeBase;

  /// Total cost paid in [quoteSymbol] units (== `price * sizeBase`,
  /// pre-computed at insert time so the UI doesn't have to redo the
  /// multiplication on every paint).
  final double costQuote;

  /// Quote currency the fill was paid in (e.g. `USDT`). Stored on the
  /// fill itself so the inspect modal stays correct even if the asset
  /// detail screen later supports multiple quote currencies.
  final String quoteSymbol;

  final DateTime timestamp;

  @override
  List<Object?> get props => <Object?>[
        id,
        symbol,
        side,
        price,
        sizeBase,
        costQuote,
        quoteSymbol,
        timestamp,
      ];
}

/// Hive type IDs for [Fill] + [FillSide]. Centralized so future model
/// types pick the next free id without grepping.
const int kFillTypeId = 1;
const int kFillSideTypeId = 2;

/// Hand-written adapter for [FillSide].
///
/// On-disk wire format: a single byte (the enum index). Adding a new
/// case is safe as long as it's appended; reordering would corrupt
/// existing rows.
class FillSideAdapter extends TypeAdapter<FillSide> {
  @override
  final int typeId = kFillSideTypeId;

  @override
  FillSide read(BinaryReader reader) {
    final int index = reader.readByte();
    if (index < 0 || index >= FillSide.values.length) {
      // Unknown future value (forward-compat read on an older client).
      // Default to buy — the safe option, matches today's emission.
      return FillSide.buy;
    }
    return FillSide.values[index];
  }

  @override
  void write(BinaryWriter writer, FillSide obj) {
    writer.writeByte(obj.index);
  }
}

/// Hand-written adapter for [Fill].
///
/// On-disk wire format: `numberOfFields` (byte), then for each field
/// a `(fieldId byte, value)` pair. Field IDs are stable forever — to
/// add a new field, pick the next unused id and bump
/// `numberOfFields`. To remove a field, leave its id reserved and
/// stop writing it (older readers will simply ignore it once it
/// disappears from the stream because they read by id, not by
/// position).
class FillAdapter extends TypeAdapter<Fill> {
  @override
  final int typeId = kFillTypeId;

  @override
  Fill read(BinaryReader reader) {
    final int numberOfFields = reader.readByte();
    final Map<int, dynamic> fields = <int, dynamic>{
      for (int i = 0; i < numberOfFields; i++) reader.readByte(): reader.read(),
    };
    return Fill(
      id: fields[0] as String,
      symbol: fields[1] as String,
      side: fields[2] as FillSide,
      price: fields[3] as double,
      sizeBase: fields[4] as double,
      costQuote: fields[5] as double,
      quoteSymbol: fields[6] as String,
      timestamp: fields[7] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, Fill obj) {
    writer
      ..writeByte(8)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.symbol)
      ..writeByte(2)
      ..write(obj.side)
      ..writeByte(3)
      ..write(obj.price)
      ..writeByte(4)
      ..write(obj.sizeBase)
      ..writeByte(5)
      ..write(obj.costQuote)
      ..writeByte(6)
      ..write(obj.quoteSymbol)
      ..writeByte(7)
      ..write(obj.timestamp);
  }
}

/// Registers both adapters with Hive. Idempotent — calling this more
/// than once (e.g. across hot restart in dev) is a no-op for already-
/// registered type IDs.
void registerFillAdapters() {
  if (!Hive.isAdapterRegistered(kFillSideTypeId)) {
    Hive.registerAdapter(FillSideAdapter());
  }
  if (!Hive.isAdapterRegistered(kFillTypeId)) {
    Hive.registerAdapter(FillAdapter());
  }
}
